### ISSUE TITLE
Dispenser für niemandem mehr zugänglich

### ISSUE THREAD

**Issue by Theyarenotyou** [DieReicheErethons/DungeonsXL#10]
Viele Fallen bestehen aus Dispensern. Klar, man könnte Lianen davorhängen aber das,
- sieht hässlich aus
- geht nicht immer
- bringt einige Glitches mit sich

Vielleicht könnte man den Usern die Permissions nehmen, um auf Dispenser zuzugreifen?

**Comment by DieReicheErethons** [comment]
Sicher wird gemacht
