### ISSUE TITLE
/dxl leave without saving

### ISSUE THREAD

**Issue by Sn0wStorm** [DieReicheErethons/DungeonsXL#35]
Wenn man ohne zu speichern ein Dungeon aus der editworld verlässt und die welt sich entlädt, so werden die neuen Schildpositionen gespeichert (die Schilder aber nicht).

Wenn man dann ein neues Schild dort hinsetzt, wird dieses zwei mal getriggert.

**Comment by Grafe** [comment]
Funktioniert dies eigentlich mittlerweile?

**Comment by Sn0wStorm** [comment]
Ja, die Welt wird nur noch beim Entladen in den dungeons Ordner kopiert, nicht bei jedem speichern, somit ist das Problem gelöst.
Da dxl leave die Welt ja nun auch speichert, werde ich den Befehl dxl escape hinzufügen, der eine Welt ohne speichern verlässt

**Comment by Grafe** [comment]
Nice danke!
